NET:
  EMB_NN: 'pointnet'
  POINTER: 'transformer'
  HEAD: 'svd'
  EMB_DIMS: 512
  N_BLOCKS: 1
  N_HEADS: 4
  FF_DIMS: 1024
  DROPOUT: 0.0

SEED: 1234

TRAINING:
  OVERFIT: False
  BATCH_SIZE: 16
  EPOCHS: 250
  LR: 1e-3
  MOMENTUM: 0.9
  CYCLE: False
  NUM_POINTS: 1024
  FACTOR: 4


TESTING:
  BATCH_SIZE: 5
  MODEL: '/home/tonyw/Documents/ml_3d_project/checkpoints/01_16-21_05_21/models/model.227.t7'