NET:
  EMB_NN: 'dgcnn'
  POINTER: 'identity'
  HEAD: 'mlp'
  EMB_DIMS: 512
  N_BLOCKS: 1
  N_HEADS: 4
  FF_DIMS: 1024
  DROPOUT: 0.0

SEED: 1234

TRAINING:
  OVERFIT: False
  BATCH_SIZE: 10
  EPOCHS: 250
  LR: 1e-3
  MOMENTUM: 0.9
  CYCLE: False
  NUM_POINTS: 1024
  FACTOR: 4


TESTING:
  BATCH_SIZE: 10
  MODEL: 'checkpoints/01_18-08_46_57/models/model.latest.t7'