name: Make_Proposal

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - uses: actions/checkout@v3
    - name: Build pdf
      working-directory: ./proposal
      run: make pdf