name: Make_Proposal

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - uses: actions/checkout@v2
    - working-directory: ./proposal

    - name: Build pdf
      run: make pdf